### PR TITLE
Update main.blocks, main.ts

### PR DESCRIPTION
**Pull request by kroznai**

### CODE REVIEW

**Review by B4-Bingo — APPROVED** [review]
Making an attempt to merge the changes by approving hte pull request.

**Comment by B4-Bingo** [comment]
Well, the good news is I have a fix. The bad news is it's not something the students can do themselves since I had to install GitHub desktop. I'm going to try one more thing, but I'm not sure if there's a viable workaround for this.

**Comment by kroznai** [comment]
How do you do it?  Can I install github desktop on my computer & do it
there?

*Ms. Katie Roznai* *(she/her)*
Chemistry & Computer Science Teacher
Girls Who Code & Garden Club Facilitator
Learning Garden Team Member
World Language High School <https://wl.lvlhs.org/index.jsp>
Little Village Lawndale Campus <https://www.lvlhs.org/>
Chicago Public Schools <https://cps.edu/Pages/home.aspx>
(773) 535-4335
***@***.***

"Education is not the learning of facts, but the training of the mind to
think."  --Albert Einstein

**Comment by B4-Bingo** [comment]
It should definitely be doable if you’re able to install GitHub Desktop (depending on what the admins let you install), and Visual Studio Code. You can pull down the Pull Request on GitHub Desktop, but it doesn’t seem like you can edit it there, naturally. So Visual Studio Code is the free, open source version of Visual Studio, and that worked on the text files that are behind some of the MakeCode files. I can demo it tomorrow if you can put together another sample conflict that you can’t resolve online. I couldn’t roll back to recreate the conflict, and then got sidetracked by a couple of other things. Worst case is if weather/traffic is bad, I can do a screen share/help remotely.Sent from my iPadOn Jan 26, 2023, at 09:59, kroznai ***@***.***> wrote:﻿
How do you do it?  Can I install github desktop on my computer & do it
there?

*Ms. Katie Roznai* *(she/her)*
Chemistry & Computer Science Teacher
Girls Who Code & Garden Club Facilitator
Learning Garden Team Member
World Language High School <https://wl.lvlhs.org/index.jsp>
Little Village Lawndale Campus <https://www.lvlhs.org/>
Chicago Public Schools <https://cps.edu/Pages/home.aspx>
(773) 535-4335
***@***.***

"Education is not the learning of facts, but the training of the mind to
think."  --Albert Einstein

**Comment by kroznai** [comment]
Yes that would be awesome!
Or at least show me how to do it, since the kids can't download github or
anything to chromebook

*Ms. Katie Roznai* *(she/her)*
Chemistry & Computer Science Teacher
Girls Who Code & Garden Club Facilitator
Learning Garden Team Member
World Language High School <https://wl.lvlhs.org/index.jsp>
Little Village Lawndale Campus <https://www.lvlhs.org/>
Chicago Public Schools <https://cps.edu/Pages/home.aspx>
(773) 535-4335
***@***.***

"Education is not the learning of facts, but the training of the mind to
think."  --Albert Einstein

**Pull request merged**
